version: "2"
services:
  webserver:
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
  db:
    image: postgres:${MOODLE_DOCKER_DB_VERSION:-14}
    environment:
      POSTGRES_USER: "${MOODLE_DOCKER_DBUSER}"
      POSTGRES_PASSWORD: "${MOODLE_DOCKER_DBPASS}"
      POSTGRES_DB: "${MOODLE_DOCKER_DBNAME}"
    ports:
      - "${MOODLE_DOCKER_PG_PORT}:5432"
