services:
  webserver:
    environment:
      MOODLE_DOCKER_BROWSER: firefox
  selenium:
    image: "selenium/standalone-firefox${MOODLE_DOCKER_SELENIUM_SUFFIX:-}:${MOODLE_DOCKER_BROWSER_TAG}"
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html:rw"
      - /dev/shm:/dev/shm
